projects:
  - id: project1
    name: "Project flowinsight tebyan"
    password: "tebyan"
    upstream_url: "http://127.0.0.1:9000"
  
  - id: project2
    name: "Project ibscloud"
    password: "ibscloud"
    upstream_url: "http://127.0.0.1:9800"

  - id: project3
    name: "Project local"
    password: "xcr9"
    upstream_url: "http://127.0.0.1:9900"

security:
  secret_key: "xcr9session"
  session_expire_minutes: 60

cors:
  allowed_origins:
    - "https://mithrillog.xcr9.site"
    - "http://localhost:9000"
    - "http://127.0.0.1:9000"
